#
# NOTE: THIS DOCKERFILE IS GENERATED VIA "apply-templates.sh"
#
# PLEASE DO NOT EDIT IT DIRECTLY.
#

# Use Python 3.12 slim image
FROM python:3.12-slim

# Load env vars from caprover settings
ARG MAX_PRODUCTS

ARG DB_HOST
ARG DB_USER
ARG DB_PASSWORD
ARG DB_NAME
ARG DB_PORT

ARG USE_THREADING

ARG CROWLBASE_TOKEN

ARG TEST_HOST
ARG TEST_PORT
ARG TEST_API_KEY

ARG EMAIL_USER
ARG EMAIL_PASSWORD
ARG TO_EMAILS

ARG SAVE_HTML

ARG SECRET_KEY

ARG REFERRAL_HOST
ARG REFERRAL_API_KEY

ARG ROTATTION_LINKS_SYSTEM
ARG ROTATION_LINKS_USER
ARG ADS_RELATION
ARG RECENT_SEARCHES_NUM
ARG POST_BOT_HOST
ARG HOST

ENV MAX_PRODUCTS=$MAX_PRODUCTS

ENV DB_HOST=$DB_HOST
ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_NAME=$DB_NAME
ENV DB_PORT=$DB_PORT


ENV USE_THREADING=$USE_THREADING

ENV CROWLBASE_TOKEN=$CROWLBASE_TOKEN

ENV TEST_HOST=$TEST_HOST
ENV TEST_PORT=$TEST_PORT
ENV TEST_API_KEY=$TEST_API_KEY

ENV EMAIL_USER=$EMAIL_USER
ENV EMAIL_PASSWORD=$EMAIL_PASSWORD
ENV TO_EMAILS=$TO_EMAILS

ENV SAVE_HTML=$SAVE_HTML

ENV SECRET_KEY=$SECRET_KEY

ENV REFERRAL_HOST=$REFERRAL_HOST
ENV REFERRAL_API_KEY=$REFERRAL_API_KEY

ENV ROTATTION_LINKS_SYSTEM=$ROTATTION_LINKS_SYSTEM
ENV ROTATION_LINKS_USER=$ROTATION_LINKS_USER
ENV ADS_RELATION=$ADS_RELATION
ENV RECENT_SEARCHES_NUM=$RECENT_SEARCHES_NUM
ENV POST_BOT_HOST=$POST_BOT_HOST
ENV HOST=$HOST



# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . /app/

# Install system dependencies (e.g., for PostgreSQL support)
RUN apt-get update && apt-get install -y \
    libpq-dev gcc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Expose the port that Flask will run on
EXPOSE 5000

# Command to run Flask in production with Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]